"""audit_compliance — append-only audit trail, KYC scaffolding, consent records (REG-01)

Before this there was no way to answer "who changed this project's
target" or "who removed this member" — update_project/update_chama loop
setattr over the payload with no record of actor, time or previous value,
and remove_member hard-deletes the row outright. There was also no
customer-identification scaffolding and no persisted evidence that a user
ever agreed to the Terms of Service / Privacy Policy, despite the mobile
register screen gating its submit button on exactly that checkbox.

After this: `audit_events` is written automatically by a SQLAlchemy
before_flush/after_flush hook (app/core/audit.py) for every
create/update/delete on User, Chama, ChamaMember, Project, Contribution
and Budget — coverage doesn't depend on a handler remembering to log
anything. `kyc_profiles` gives every user a TIER0 row at registration but
is deliberately not read or enforced anywhere yet (see the docstring on
KycProfile in app/models/compliance.py — there's no verification flow to
move a user off TIER0, so enforcing a hard cap now would be a silent,
unappealable product change). `consent_records` is written once per
registration by app/routers/auth.py, capturing the policy version, IP and
user agent alongside the grant.

Revision ID: 003_audit_compliance
Revises: 002_token_security
Create Date: 2026-08-04 12:40:01.392883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003_audit_compliance'
down_revision: Union[str, Sequence[str], None] = '002_token_security'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_events', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('policy', sa.String(length=40), nullable=False),
    sa.Column('policy_version', sa.String(length=20), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('kyc_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('TIER0', 'TIER1', 'TIER2', name='kyctier'), nullable=False),
    sa.Column('id_type', sa.Enum('NATIONAL_ID', 'PASSPORT', 'ALIEN_ID', name='iddocumenttype'), nullable=True),
    sa.Column('id_number_hash', sa.String(length=64), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=40), nullable=True),
    sa.Column('screening_status', sa.Enum('PENDING', 'CLEARED', 'FLAGGED', name='screeningstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_kyc_profiles_id_number_hash'), 'kyc_profiles', ['id_number_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_profiles_id_number_hash'), table_name='kyc_profiles')
    op.drop_table('kyc_profiles')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_index('ix_audit_actor', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
