"""contribution_idempotency_constraints — DB-enforced idempotency (PAY-02)

The handler applied a callback's credit unconditionally: no check that the
contribution was still PENDING, no unique constraint linking a provider
receipt to a single credit, and no idempotency key. Payment providers
guarantee at-least-once delivery, not exactly-once — Safaricom retries
when a callback is slow or returns non-2xx, so duplicate callbacks are
routine in production, not exceptional. FIN-02's ledger already closes
this for the ledger entry itself (UNIQUE(contribution_id, direction));
this migration adds the matching guarantee at the contribution level so a
provider receipt can never settle two different contributions, and a
composite index for the (project_id, status) access pattern the
reconciliation sweep (PAY-03) and dashboards need.

Note: `alembic revision --autogenerate` does not detect CHECK constraint
additions by default, so `ck_contribution_amount_positive` is added here
by hand rather than autogenerated.

Revision ID: 005_contribution_idempotency
Revises: 004_callback_verification
Create Date: 2026-07-31
"""
from typing import Sequence, Union

from alembic import op


revision: str = "005_contribution_idempotency"
down_revision: Union[str, Sequence[str], None] = "004_callback_verification"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index("ix_contributions_project_status", "contributions", ["project_id", "status"], unique=False)
    op.create_unique_constraint("uq_contribution_provider_receipt", "contributions", ["provider", "provider_reference"])
    op.create_check_constraint("ck_contribution_amount_positive", "contributions", "amount > 0")


def downgrade() -> None:
    op.drop_constraint("ck_contribution_amount_positive", "contributions", type_="check")
    op.drop_constraint("uq_contribution_provider_receipt", "contributions", type_="unique")
    op.drop_index("ix_contributions_project_status", table_name="contributions")
